apiVersion: v2
name: plausible-analytics
description: A Helm Chart for Plausible Analytics - a simple and privacy-friendly alternative to Google Analytics
type: application
version: 0.3.0
appVersion: v1.4.4
home: https://plausible.io/
icon: https://docs.plausible.io/img/logo.svg
keywords:
  - plausible analytics
  - analytics
sources:
  - https://0xacab.org/varac/plausible-helm-chart
  - https://hub.docker.com/r/plausible/analytics
  - https://github.com/plausible/analytics
maintainers:
  - name: Varac
    url: https://varac.net
  - name: Vadim Bauer
    url: https://8gears.com
